
spring:
    profiles:
        
    application: 
        name: vtgw
    thymeleaf:
        cache: false
        check-template-location: true
        mode: HTML
        encoding: UTF-8
        content-type: text/html
        prefix:  classpath:resources/static/resources/templates/
        suffix: .html
    data: 
      mongo:
        repositories: 
          enabled: true
      mongodb:
        uri: mongodb+srv://admin:"${mongoDBPass}"@varnatravelguide-z24ti.gcp.mongodb.net/test?retryWrites=true&w=majority
        database: VarnaTravelGuide

security:
   basic:
      oauth2: 
#         sso:
#          login-path: /login
         resource: 
            userInfoUri: https://www.googleapis.com/varnatravelguideweb
            preferTokenInfo: true
         client:
            useCurrentUri: false
            preEstablishedRedirectUri: http://localhost:8080/index
            registratsion:
              google:
                clientId: ${googleClientId}
                clientSecret: ${googleClientSecret}
                
                accessTokenUri: https://www.googleapis.com/oauth2/v3/token
                userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
                scope:  
                  - email
                  - profile
                  - openid
       
logging:
  level:
    root: DEBUG
    com.memorynotfound: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG