spring:
    application: 
        name: VarnaTravelGuideWeb
    datasource:
        url: jdbc:mysql://localhost:3306/spring_social?useSSL=false
        username: root
        password: callicoder
        
    data:
      mongodb:
        host: mongoserver
        port: "27017"
        authentication: database=admin
        username: root
        password: root
        database: VarnaTravelGuide

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 496244831513-h489l6l21o4ua5pgfb6vrbt921rpb5t2.apps.googleusercontent.com
              clientSecret: oJAmHqdLty7v97UysF37_AfI 
              redirectUriTemplate: " http://localhost:8081/oauth2/callback/google"
              scope:
                - email
                - profile
            
          provider:
             google:
              authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
              tokenUri: https://www.googleapis.com/oauth2/v4/token


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC 
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
