spring:
    security:
       user:
         name: user
         password: password
    data: 
      mongo:
        repositories: 
          enabled: true	
      mongodb:
        uri: mongodb+srv://admin:admin@varnatravelguide-z24ti.gcp.mongodb.net/test?retryWrites=true&w=majority
        database: varnaTravelGuideDB
     
logging:  
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.mongodb: INFO
