
spring:
    application: 
        name: vtgw
    security:
        user:
          name: user
          password: password
    thymeleaf:
        cache: false
        check-template-location: true
        mode: HTML
        encoding: UTF-8
        content-type: text/html
    data: 
      mongo:
        repositories: 
          enabled: true
      mongodb:
        uri:  mongodb+srv://admin:v9rlO0w1QoiWw8Bt@varnatravelguide-z24ti.gcp.mongodb.net/test?retryWrites=true&w=majority
        database: VarnaTravelGuide
       
logging:  
  level:
    root: DEBUG
    com.memorynotfound: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
   