spring:
    application: 
        name: VarnaTravelGuideWeb
        
    data: 
      mongo:
        repositories: 
          enabled: true
      mongodb:
        uri: mongodb+srv://admin:"ronaldo7#"@varnatravelguide-z24ti.gcp.mongodb.net/test?retryWrites=true&w=majority
#        host: 
#        port: 
#        authentication-database:
#        username: 
#        password: 
        database: VarnaTravelGuide
        
    security:
      oauth2:
        client:
            registration:
              google:
                clientId: 496244831513-h489l6l21o4ua5pgfb6vrbt921rpb5t2.apps.googleusercontent.com
                clientSecret: oJAmHqdLty7v97UysF37_AfI
                
                accessTokenUri: https://www.googleapis.com/oauth2/v3/token
                userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
                scope:  
                  - email
                  - profile
            useCurrentUri: false
            
#             provider:
#               google:
#                authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#                tokenUri: https://www.googleapis.com/oauth2/v4/token

        resource: 
            userInfoUri:  https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
logging:
    level:
        org:
          springframework:
                web: DEBUG

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC 
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
