#server:
#    port: 8080
#    session:
#      cookie:
#        name: UISESSION    
spring:
    application: 
        name: vtgw
    thymeleaf:
        cache: false
        check-template-location: true
        mode: HTML
        encoding: UTF-8
        content-type: text/html
        prefix:  classpath:public/templates/
        suffix: .html
    data: 
      mongo:
        repositories: 
          enabled: true
      mongodb:
        uri: mongodb+srv://admin:"${mongoDBPass}"@varnatravelguide-z24ti.gcp.mongodb.net/test?retryWrites=true&w=majority
        database: VarnaTravelGuide
        
#        host: 
#        port: 
#        authentication-database:
#        username: 
#        password: 

security:
   basic:
      enabled: false 
      oauth2: 
         resource: 
            userInfoUri: https://www.googleapis.com/varnatravelguideweb
            preferTokenInfo: false
         client:
            useCurrentUri: false
            preEstablishedRedirectUri: http://localhost:8080/index
            registratsion:
              google:
                clientId: ${googleClientId}
                clientSecret: ${googleClientSecret}
                
                accessTokenUri: https://www.googleapis.com/oauth2/v3/token
                userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
                scope:  
                  - email
                  - profile
      sso:
       login-path: /login
logging:
    level:
       org: 
         springframework:
            web: DEBUG 
            security: DEBUG 

#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC 
#    tokenExpirationMsec: 864000000
#  oauth2:
#    authorizedRedirectUris:
#        http://localhost:3000/oauth2/redirect
